# -*- coding: utf-8 -*-
"""
doc_meta.py — свойства документа (.docx): показать / привести к профилю владельца.

ЗАЧЕМ. Процессуальный документ подписывает и выпускает следователь — он и есть автор.
Но в свойствах файла остаются следы ИНСТРУМЕНТА и ДОНОРА, которых там быть не должно:
  · make_docx (python-docx):  dc:creator="python-docx", dc:description="generated by
    python-docx", даты 2013-12-23 (дефолтный шаблон библиотеки), Application
    "Microsoft Macintosh Word 14" — полный набор маркеров;
  · документ от донора: чужой автор («Олег», «ХХХХХ»), чужая Company («ГВП»),
    чужой Title («Ф-2», обрывки) — python-docx сохраняет core.xml донора как есть.
Аудит 07.08.2026 нашёл всё это в БОЕВЫХ файлах (в т.ч. в допросе, ушедшем в дело).

ЭТАЛОН — собственноручные файлы владельца, набранные в его Word:
  dc:creator / cp:lastModifiedBy = подтверждённое значение профиля; по умолчанию пусто,
  Application "Microsoft Office Word", AppVersion "16.0000", Template "Normal",
  Company/Manager/Title пустые. Профиль читается из константы.json → "метаданные"
  (если блока нет — используются значения по умолчанию ниже).

ЧТО НЕ ДЕЛАЕТ. Не трогает содержимое, таблицы, поля формы, защиту, колонтитулы.
Работает только с docProps/core.xml и docProps/app.xml (+ удаляет docProps/custom.xml,
если появился). Пересборка zip побайтово сохраняет все остальные части.

CLI:
  python doc_meta.py show  <файл.docx>            — показать свойства
  python doc_meta.py clean <файл.docx> [ещё файлы] — привести к профилю (правка на месте)
  python doc_meta.py sweep <папка>    [--apply]    — пакетно; без --apply только отчёт
"""
import os
import re
import sys
import json
import shutil
import zipfile
import datetime

try:
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stderr.reconfigure(encoding="utf-8")
except Exception:
    pass

HERE = os.path.dirname(os.path.abspath(__file__))

# Профиль по умолчанию — снят с СОБСТВЕННОРУЧНЫХ файлов владельца (аудит 07.08.2026).
DEFAULT_PROFILE = {
    "автор": "",
    "приложение": "Microsoft Office Word",
    "версия_приложения": "16.0000",
    "шаблон": "Normal",
}

# Маркеры, при виде которых даты created/modified считаются НЕ доверенными
# (дефолтный шаблон python-docx датирован 2013-12-23).
_SUSPECT_DATES = ("2013-12-23",)

_NS_DECL = {
    "cp": 'xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties"',
    "dc": 'xmlns:dc="http://purl.org/dc/elements/1.1/"',
    "dcterms": 'xmlns:dcterms="http://purl.org/dc/terms/"',
    "dcmitype": 'xmlns:dcmitype="http://purl.org/dc/dcmitype/"',
    "xsi": 'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
}
_NSC = " ".join(_NS_DECL.values())


def profile():
    """Профиль метаданных: константы.json → "метаданные", иначе дефолт."""
    p = dict(DEFAULT_PROFILE)
    for cand in (os.environ.get("SK_CONSTANTS", ""), os.path.join(HERE, "константы.json"),
                 os.path.join(HERE, "..", "константы.json")):
        try:
            with open(cand, encoding="utf-8") as f:
                data = json.load(f)
            p.update(data.get("метаданные") or {})
            break
        except Exception:
            continue
    return p


def _get(xml, tag):
    m = re.search(rf"<{tag}[^>]*>(.*?)</{tag}>", xml, re.S)
    if m:
        return m.group(1).strip()
    return "" if re.search(rf"<{tag}[^>]*/>", xml) else None


def read_props(path):
    out = {}
    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        core = z.read("docProps/core.xml").decode("utf-8") if "docProps/core.xml" in names else ""
        app = z.read("docProps/app.xml").decode("utf-8") if "docProps/app.xml" in names else ""
    for t in ("dc:creator", "cp:lastModifiedBy", "dc:title", "dc:subject", "dc:description",
              "cp:keywords", "cp:category", "cp:revision", "dcterms:created", "dcterms:modified"):
        v = _get(core, t)
        if v is not None:
            out[t] = v
    for t in ("Application", "AppVersion", "Company", "Manager", "Template", "TotalTime"):
        v = _get(app, t)
        if v is not None:
            out[t] = v
    out["custom.xml"] = "docProps/custom.xml" in names
    return out


def diagnose(path, prof=None):
    """Список проблем в свойствах файла (пусто = чисто)."""
    prof = prof or profile()
    pr = read_props(path)
    bad = []
    author = prof["автор"]
    lowset = ("python-docx",)
    for tag in ("dc:creator", "cp:lastModifiedBy"):
        v = (pr.get(tag) or "").strip()
        if v.lower() in lowset or (v and v != author):
            bad.append(f"{tag} = {v!r} (должно быть {author!r})")
        elif not v and author:
            bad.append(f"{tag} пуст (должно быть {author!r})")
    if (pr.get("dc:description") or "").strip():
        bad.append(f"dc:description = {pr['dc:description']!r} (должно быть пусто)")
    if (pr.get("dc:title") or "").strip():
        bad.append(f"dc:title = {pr['dc:title']!r} (должно быть пусто)")
    for tag in ("Company", "Manager", "cp:keywords", "cp:category", "dc:subject"):
        if (pr.get(tag) or "").strip():
            bad.append(f"{tag} = {pr[tag]!r} (должно быть пусто)")
    if pr.get("Application") != prof["приложение"] or pr.get("AppVersion") != prof["версия_приложения"]:
        bad.append(f"Application = {pr.get('Application')!r}/{pr.get('AppVersion')!r} "
                   f"(эталон {prof['приложение']!r}/{prof['версия_приложения']!r})")
    if (pr.get("Template") or "") not in (prof["шаблон"], prof["шаблон"] + ".dotm"):
        bad.append(f"Template = {pr.get('Template')!r} (эталон {prof['шаблон']!r})")
    for tag in ("dcterms:created", "dcterms:modified"):
        v = pr.get(tag) or ""
        if any(s in v for s in _SUSPECT_DATES):
            bad.append(f"{tag} = {v!r} (дата дефолтного шаблона python-docx)")
    if pr.get("custom.xml"):
        bad.append("присутствует docProps/custom.xml")
    return bad


def _ensure_ns(xml, *prefixes):
    """Дописать в корневой тег объявления пространств имён, если их там нет.

    ⛔ Иначе получается НЕВАЛИДНЫЙ core.xml: у документа объявлены только `cp` и `dc`,
    а мы добавляем `dcterms:created` с `xsi:type` — и парсер падает на «unbound prefix».
    Найдено 14.08.2026 сплошной проверкой 4109 .docx (1 файл был битым)."""
    m = re.search(r"<([A-Za-z0-9]+:coreProperties|Properties)\b[^>]*>", xml)
    if not m:
        return xml
    head = m.group(0)
    add = "".join(" " + d for p, d in _NS_DECL.items()
                  if p in prefixes and f"xmlns:{p}=" not in head)
    if not add:
        return xml
    return xml[:m.start()] + head[:-1] + add + ">" + xml[m.end():]


def _set(xml, tag, value, attrs=""):
    """Заменить/добавить простой тег в xml-строке свойств."""
    esc = (value.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;"))
    # префиксы, которые вводит сам тег и его атрибуты, должны быть объявлены в корне
    xml = _ensure_ns(xml, *re.findall(r"([A-Za-z0-9]+):", tag + " " + attrs))
    if re.search(rf"<{tag}[^>]*>.*?</{tag}>", xml, re.S):
        return re.sub(rf"<{tag}[^>]*>.*?</{tag}>", f"<{tag}{attrs}>{esc}</{tag}>", xml, flags=re.S)
    if re.search(rf"<{tag}[^>]*/>", xml):
        return re.sub(rf"<{tag}[^>]*/>", f"<{tag}{attrs}>{esc}</{tag}>", xml)
    # добавить перед закрывающим корневым
    return re.sub(r"(</cp:coreProperties>|</Properties>)", f"<{tag}{attrs}>{esc}</{tag}>\\1", xml)


def _drop(xml, tag):
    xml = re.sub(rf"<{tag}[^>]*>.*?</{tag}>", "", xml, flags=re.S)
    return re.sub(rf"<{tag}[^>]*/>", "", xml)


def clean(path, backup=False):
    """Привести свойства файла к профилю владельца. Возвращает список правок."""
    prof = profile()
    problems = diagnose(path, prof)
    if not problems:
        return []

    with zipfile.ZipFile(path) as z:
        names = z.namelist()
        items = {n: z.read(n) for n in names}
        infos = {n: z.getinfo(n) for n in names}

    core = items.get("docProps/core.xml", b"").decode("utf-8")
    app = items.get("docProps/app.xml", b"").decode("utf-8")
    if not core:
        core = (f'<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\r\n'
                f'<cp:coreProperties {_NSC}></cp:coreProperties>')

    author = prof["автор"]
    core = _set(core, "dc:creator", author)
    core = _set(core, "cp:lastModifiedBy", author)
    for t in ("dc:description", "dc:title", "dc:subject", "cp:keywords", "cp:category"):
        core = _drop(core, t)
    # даты: подозрительные (шаблон python-docx) → mtime файла; живые не трогаем
    mtime = datetime.datetime.fromtimestamp(os.path.getmtime(path), datetime.timezone.utc)
    stamp = mtime.strftime("%Y-%m-%dT%H:%M:%SZ")
    for t in ("dcterms:created", "dcterms:modified"):
        v = _get(core, t) or ""
        if any(s in v for s in _SUSPECT_DATES) or not v:
            core = _drop(core, t)
            core = _set(core, t, stamp, ' xsi:type="dcterms:W3CDTF"')

    if app:
        app = _set(app, "Application", prof["приложение"])
        app = _set(app, "AppVersion", prof["версия_приложения"])
        app = _set(app, "Template", prof["шаблон"])
        for t in ("Company", "Manager"):
            app = _drop(app, t)

    if backup:
        shutil.copy2(path, path + ".bak_meta")

    tmp = path + ".tmp_meta"
    with zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as z:
        for n in names:
            if n == "docProps/custom.xml":
                continue                      # выкинуть кастомные свойства целиком
            if n == "docProps/core.xml":
                data = core.encode("utf-8")
            elif n == "docProps/app.xml":
                data = app.encode("utf-8")
            else:
                data = items[n]
            zi = zipfile.ZipInfo(n, date_time=infos[n].date_time)
            zi.compress_type = zipfile.ZIP_DEFLATED
            zi.external_attr = infos[n].external_attr
            z.writestr(zi, data)
    # целостность: tmp обязан быть валидным zip с тем же составом частей
    ok = zipfile.is_zipfile(tmp)
    if ok:
        with zipfile.ZipFile(tmp) as z:
            new_names = set(z.namelist())
        expect = set(names) - {"docProps/custom.xml"}
        ok = new_names == expect
    if not ok:
        os.remove(tmp)
        raise IOError(f"doc_meta: пересборка дала битый/неполный zip, файл НЕ тронут: {path}")
    # сохранить mtime файла (правка свойств не должна «трогать» файл по времени)
    st = os.stat(path)
    os.replace(tmp, path)
    os.utime(path, (st.st_atime, st.st_mtime))
    return problems


def sweep(root, apply=False):
    total, dirty, fixed = 0, 0, 0
    for dp, dn, fns in os.walk(root):
        dn[:] = [d for d in dn if d not in ("_Архив", "__pycache__")]
        for fn in fns:
            if not fn.lower().endswith(".docx") or fn.startswith("~$"):
                continue
            p = os.path.join(dp, fn)
            total += 1
            try:
                probs = diagnose(p)
            except Exception:
                continue
            if not probs:
                continue
            dirty += 1
            rel = os.path.relpath(p, root)
            print(f"  {rel[:100]}")
            for b in probs[:4]:
                print(f"      · {b}")
            if apply:
                clean(p)
                fixed += 1
    print(f"\nвсего .docx: {total} | с проблемами: {dirty} | исправлено: {fixed}"
          + ("" if apply else "  (без --apply только отчёт)"))
    return dirty


def main():
    if len(sys.argv) > 1 and sys.argv[1] in ("-h", "--help", "/?", "help"):
        print(__doc__)
        return 0
    if len(sys.argv) < 3:
        print(__doc__)
        return 2
    cmd, target = sys.argv[1], sys.argv[2]
    if cmd == "show":
        for k, v in read_props(target).items():
            print(f"  {k:<22} = {v!r}")
        bad = diagnose(target)
        print("\nчисто ✓" if not bad else "проблемы:\n  " + "\n  ".join(bad))
        return 1 if bad else 0
    if cmd == "clean":
        for t in sys.argv[2:]:
            fixes = clean(t)
            print(f"{os.path.basename(t)}: " +
                  ("уже чисто ✓" if not fixes else f"исправлено {len(fixes)}: " + "; ".join(fixes[:3])))
        return 0
    if cmd == "sweep":
        return 1 if sweep(target, apply="--apply" in sys.argv) and "--apply" not in sys.argv else 0
    print(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
